### ISSUE TITLE
Feedback & suggested improvements

### ISSUE THREAD

**Issue by unquietwiki** [Tecnativa/docker-postfix-relay#1]
Was looking for an SMTP agent to combine with a Docker instance. Found this, but it seems to hiccup in my test environment at least.

1. Suggested **docker-compose.yaml** ; based in part on other SMTP docker stuff I found. This also documents the fact that postfix fires up as port 25.

```
smtp:
  restart: always
  build: .
  ports:
   - "25:25"
  environment:
    MAIL_RELAY_PORT: '587'
    MAIL_RELAY_HOST: 'smtp-relay.gmail.com'
    MAIL_RELAY_USER: 'nobody@gmail.com'
    MAIL_RELAY_PASS: 'Password'
    RELAYHOST: 'smtp-relay.gmail.com'
```

2. The content in the **Dockerfile** for building up the Postfix configuration: it may need adjustment to allow Docker networks from 172.17.0.1/12 and/or 172.18.0.1/12 to connect (saw that come up in the logs at least once).

3. I tried to munge in additional environment values into the Postfix config. Not sure that's being successful. May have more luck using the docker-compose to import a customized main.cf ?
